 cp mpd.cpp newfiles
 cp behave.cpp newfiles
 cp los.cpp newfiles
 cp osi\terrlow.h newfiles\osi
 cp osi\tercache.h newfiles\osi
 cp osi\tercache.cpp newfiles\osi
 cp osi\grbuff.cpp newfiles\osi
 cp osi\fmath.h newfiles\osi
 cp osi\grddraw.cpp newfiles\osi
 cp osi\color.cpp newfiles\osi
 cp osi\terrain.h newfiles\osi
 cp osi\grvars.h newfiles\osi
 cp osi\terrain.cpp newfiles\osi
 cp osi\terrlow.cpp newfiles\osi
 cp osi\3ddriver.h newfiles\osi
 cp osi\family.cpp newfiles\osi
 cp osi\3ddriver.cpp newfiles\osi
 cp osi\grd3d.cpp newfiles\osi
 cp osi\fmath.cpp newfiles\osi
 cp osi\simland.cpp newfiles\osi
 cp osi\grvars.cpp newfiles\osi
 cp osi\simland.h newfiles\osi