// keymapid.h

#ifndef __KEYMAPID_HEADER__
#define __KEYMAPID_HEADER__

// ordinal values for keymaps info tip offset
//
//

#define KID_NOTRANSLATION						0
#define	KID_COMMAND_HUD							1
#define KID_UNUSED								2
#define	KID_COMMAND_RADAR						3
#define KID_QUEUE_BETTY							4
#define	KID_TOGGLE_3DFX							5
#define KID_TOGGLE_3DFXDEBUG					6
#define	KID_TOGGLE_3DFXGAMMA					7
#define KID_AUTOPILOT							8
#define	KID_TOGGLE_TF							9
#define KID_SPEEDBREAK							10
#define	KID_DISPLAY_FPS							11
#define KID_PAUSE								12
#define	KID_TOGGLE_FLAPS						13
#define KID_TOGGLE_GEAR							14
#define	KID_TOGGLE_BRAKES						15
#define KID_NEXT_WAYPOINT						16
#define	KID_CAMERA_QUICK_OUT					17
#define KID_CAMERA_QUICK_IN						18
#define	KID_CAMERA_OUT							19
#define KID_CAMERA_IN							20
#define	KID_CAM_HEADING_UP						21
#define KID_CAM_HEADING_DOWN					22
#define	KID_CAM_PITCH_UP						23
#define KID_CAM_PITCH_DOWN						24
#define	KID_TEXTURE_DETAIL						25
#define KID_DITHER_DETAIL						26
#define	KID_SUN_ANGLE_UP						27
#define KID_SUN_ANGLE_DOWN						28
#define	KID_ACM_FRONT							29
#define KID_ACM_TOGGLE_UP						30
#define	KID_ACM_TOGGLE_DWN						31
#define KID_ACM_BACK_LEFT						32
#define	KID_ACM_LEFT							33
#define KID_ACM_RIGHT							34
#define	KID_ACM_BACK_RIGHT						35
#define KID_ACM_FRONT_LEFT						36
#define	KID_ACM_FRONT_RIGHT						37
#define KID_FRONT_VIEW							38
#define	KID_FRONT_DOWN							39
#define KID_FRONTBACK_VIEW						40
#define	KID_FRONTOPEN_VIEW						41
#define KID_FRONTLEFT_VIEW						42
#define	KID_FRONTRIGHT_VIEW						43
#define KID_BACKLEFT_VIEW						44
#define	KID_BACKRIGHT_VIEW						45
#define KID_FRONTNO_VIEW						46
#define	KID_FRONTUP_VIEW						47
#define KID_CAMERA_MODE							48
#define	KID_CAM_TOGGLE_ATTACH					49
#define KID_FREE_LOOK							50
#define	KID_EYE_POINT							51
#define KID_SCREEN_CAPTURE						52
#define	KID_NEXT_PLANE							53
#define KID_CLOSEST_PLANE						54
#define	KID_DAMAGE_PLANE						55
#define KID_INC_TIME							56
#define	KID_DEC_TIME							57
#define KID_HUD_COLOR							58
#define	KID_SIM_DONE							59
#define KID_SRM_MODE							60
#define	KID_MRM_MODE							61
#define KID_MISSILE_REJECT						62
#define	KID_ACQ_SEARCH							63
#define KID_ACQ_SS								64
#define	KID_ACQ_BST								65
#define KID_ACQ_LRBST							66
#define	KID_ACQ_VTS								67
#define KID_GUN_TRIGGER							68
#define	KID_WEAPON_PICKLE						69
#define KID_REFUEL_PLANE						70
#define	KID_MASTER_MODE							71
#define KID_UFC_AA_MODE							72
#define	KID_UFC_AG_MODE							73
#define KID_UFC_NAV_MODE						74
#define	KID_UFC_INST_MODE						75
#define KID_CHAFF								76
#define	KID_FLARES								77
#define KID_WM_ENGAGE							78
#define	KID_WM_COVER							79
#define KID_WM_SANITIZE_RIGHT					80
#define	KID_WM_SANITIZE_LEFT					81
#define KID_WM_ORBIT							82
#define	KID_WM_REJOIN_FLIGHT					83
#define KID_WM_BREAK_RIGHT						84
#define	KID_WM_BREAK_LEFT						85
#define KID_WM_BREAK_HIGH						86
#define	KID_WM_BREAK_LOW						87
#define KID_WM_BRACKET_RIGHT					88
#define	KID_WM_BRACKET_LEFT						89
#define KID_WM_SPLIT_HIGH						90
#define	KID_WM_SPLIT_LOW						91
#define KID_WM_DRAG_RIGHT						92
#define	KID_WM_DRAG_LEFT						93
#define KID_WM_ATK_PRIMARY						94
#define	KID_WM_ATK_SECONDARY					95
#define KID_WM_ATK_ANY_GRND						96
#define	KID_WM_HELP								97
#define KID_WM_ATK_MY_TARGET					98
#define	KID_WM_RETURN_TO_BASE					99
#define KID_ELM_ENGAGE							100
#define	KID_ELM_SANITIZE_RIGHT					101
#define KID_ELM_SANITIZE_LEFT					102
#define	KID_ELM_COVER							103
#define KID_ELM_ORBIT							104
#define	KID_ELM_BRACKET_RIGHT					105
#define KID_ELM_BRACKET_LEFT					106
#define	KID_ELM_SPLIT_HIGH						107
#define KID_ELM_SPLIT_LOW						108
#define	KID_ELM_DRAG_RIGHT						109
#define KID_ELM_DRAG_LEFT						110
#define	KID_ELM_ATK_PRIMARY						111
#define KID_ELM_ATK_SECONDARY					112
#define	KID_ELM_ATK_ANY_GRND					113
#define KID_ELM_REJOIN_FLIGHT					114
#define	KID_ELM_RETURN_TO_BASE					115
#define KID_DIV_ENGAGE							116
#define	KID_DIV_SANITIZE_RIGHT					117
#define KID_DIV_SANITIZE_LEFT					118
#define	KID_DIV_COVER							119
#define KID_DIV_ORBIT							120
#define	KID_DIV_BRACKET_RIGHT					121
#define KID_DIV_BRACKET_LEFT					122
#define	KID_DIV_SPLIT_HIGH						123
#define KID_DIV_SPLIT_LOW						124
#define	KID_DIV_DRAG_RIGHT						125
#define KID_DIV_DRAG_LEFT						126
#define	KID_DIV_ATK_PRIMARY						127
#define KID_DIV_ATK_SECONDARY					128
#define	KID_DIV_ATK_ANY_GRND					129
#define KID_DIV_REJOIN_FLIGHT					130
#define	KID_DIV_RETURN_TO_BASE					131
#define KID_FLT_ENGAGE							132
#define	KID_FLT_RADAR_TOGGLE					133
#define KID_FLT_JAMMER_TOGGLE					134
#define	KID_FLT_STATUS							135
#define KID_FLT_WEAPON_CHK						136
#define	KID_FLT_WEDGE_FORMATION					137
#define KID_FLT_LINE_FORMATION					138
#define	KID_FLT_ECHELON_FORMATION				139
#define KID_FLT_TRAIL_FORMATION					140
#define	KID_FLT_LOOSEN_FORMATION				141
#define KID_FLT_TIGHTEN_FORMATION				142
#define	KID_FLT_ATK_PRIMARY						143
#define KID_FLT_ATK_SECONDARY					144
#define	KID_FLT_ATK_ANY_GRND					145
#define KID_FLT_SORT_BANDITS					146
#define	KID_FLT_REJOIN_FLIGHT					147
#define KID_FLT_RETURN_TO_BASE					148
#define	KID_AWACS_PICTURE						149
#define KID_AWACS_BOGEY_DOPE					150
#define	KID_AWACS_REQUEST_COVER					151
#define KID_AWACS_REQUEST_SEAD					152
#define	KID_JSTAR_CHECK_IN_OUT					153
#define KID_JSTAR_TARGET_LOC					154
#define	KID_JSTAR_NEXT_TARGET					155
#define KID_MSG_HISTORY_TOGGLE					156
#define	KID_MSG_LIKE_HUD_TOGGLE					157
#define KID_MSG_NEXT_TEXT_COLOR					158
#define	KID_MSG_NEXT_BOX_COLOR					159
#define KID_PADLOCK_MANUAL						160
#define	KID_PADLOCK_WSO							161
#define KID_PADLOCK_FRIENDLY					162
#define	KID_PADLOCK_NEXTCENTER					163
#define KID_PADLOCK_DESIGNATE					164
#define	KID_PADLOCK_GLANCE_FRONT				165
#define KID_AUTO_REFUEL							166
#define	KID_JUMP								167
#define KID_GBU15_LEFT							168
#define	KID_GBU15_RIGHT							169
#define KID_GBU15_SHORT							170
#define	KID_GBU15_LONG							171
#define KID_JAMMER								172
#define	KID_RADIO1_TRANSMIT						173
#define KID_RADIO2_TRANSMIT						174
#define	KID_RADIO1_CHANNEL						175
#define KID_RADIO2_CHANNEL						176
#define	KID_COM_MENU_CANCEL						177
#define	KID_SWITCH_COCKPIT						178
#define KID_CAMERA_WEAPON						179
#define	KID_TOGGLE_SOUND						180
#define KID_RUNNING_LIGHTS						181
#define	KID_FORMATION_LIGHTS					182
#define	KID_COM_MENU_1							183
#define	KID_COM_MENU_2							184
#define KID_COM_MENU_3							185
#define	KID_COM_MENU_4							186
#define KID_COM_MENU_5							187
#define	KID_COM_MENU_6							188
#define KID_COM_MENU_7							189
#define	KID_COM_MENU_8							190
#define KID_COM_MENU_9							191
#define	KID_COM_MENU_0							192
#define	KID_MPD_MAIN_MENU						193
#define KID_MPD1_SCROLL							194
#define	KID_MPD2_SCROLL							195
#define KID_MPD3_SCROLL							196
#define KID_MPD_INTERACTION						197
#define KID_AGPACS_GUN_RATE						198
#define	KID_AGPACS_BOMB_QUAN_10S				199
#define KID_AGPACS_BOMB_QUAN_1S					200
#define	KID_AGPACS_TGLE_BOMB_MODE				201
#define	KID_AGPACS_BOMB_OPTIONS					202
#define KID_AGPACS_BOMB_INT_100S				203
#define	KID_AGPACS_BOMB_INT_10S					204
#define KID_AGPACS_R_WING						205
#define	KID_AGPACS_R_CONFORMAL					206
#define KID_AGPACS_CENTER						207
#define	KID_AGPACS_L_WING						208
#define KID_AGPACS_L_CONFORMAL					209
#define KID_AGRADAR_DECLUTTER					210
#define	KID_AGRADAR_MODE						211
#define KID_AGRADAR_CURSOR						212
#define	KID_AGRADAR_HRM_DW_SIZE					213
#define KID_AGRADAR_PPI_SCAN					214
#define	KID_AGRADAR_RBM_RNG_INC					215
#define KID_AGRADAR_RBM_RNG_DEC					216
#define	KID_AGRADAR_RF_BAND						217
#define KID_AGRADAR_RF_CHANNEL					218
#define KID_TFLIR_FOV							219
#define	KID_TFLIR_POLARITY						220
#define KID_TFLIR_MODE							221
#define	KID_TFLIR_AREA_TRACK					222
#define KID_TFLIR_DECLUTTER						223
#define KID_GBU15_MODE							224
#define	KID_GBU15_LAUNCH_PROFILE				225
#define KID_GBU15_DECLUTTER						226
#define	KID_UNUSED1								227
#define	KID_UNUSED2								228
#define	KID_AGM65_CUE							229
#define KID_AGM65_TRACK_MODE					230
#define KID_AAPACS_GUN_RATE						231
#define KID_AARADAR_EL_SCAN						232
#define	KID_AARADAR_FRAME_STORE					233
#define KID_AARADAR_GMT_REJECT					234
#define	KID_AARADAR_HOT_COLD					235
#define KID_AARADAR_RWS_MODE					236
#define	KID_AARADAR_RGS_MODE					237
#define KID_AARADAR_VS_MODE						238
#define	KID_AARADAR_VCTR_MODE					239
#define KID_AARADAR_TWS_MODE					240
#define	KID_AARADAR_AZ_WIDTH					241
#define KID_AARADAR_RANGE						242
#define	KID_AARADAR_ANT_UP						243
#define KID_AARADAR_ANT_DOWN					244
#define	KID_AARADAR_ANT_RIGHT					245
#define KID_AARADAR_ANT_LEFT					246
#define	KID_AARADAR_ECCM_FILTER					247
#define KID_AARADAR_RF_BAND						248
#define	KID_AARADAR_RF_CHANNEL					249
#define	KID_ANTENNA_EL_CENTER					250
#define KID_ANTENNA_EL_LEFT						251
#define	KID_ANTENNA_EL_RIGHT					252
#define	KID_GUNSIGHT_TOGGLE						253
#define KID_IFF_INTERROGATE						254
#define	KID_DESIGNATE_TARGET					255
#define KID_UNDESIGNATE_TARGET					256
#define	KID_NOSE_TRIM_DOWN						257
#define KID_NOSE_TRIM_UP						258
#define	KID_TRIM_LEFT							259
#define KID_TRIM_RIGHT							260
#define	KID_RUDDER_RIGHT_TRIM					261
#define KID_RUDDER_LEFT_TRIM					262
#define KID_TDC_UP								263
#define	KID_TDC_DOWN							264
#define KID_TDC_LEFT							265
#define	KID_TDC_RIGHT							266
#define	KID_COMMAND_STEP						267
#define KID_COMMAND_TSD							268
#define	KID_COMMAND_FLIR						269
#define	KID_MASTER_CAUTION						270
#define	KID_HSI_TACAN							271
#define KID_HSI_NAV								272
#define	KID_HSI_RANGE_INC						273
#define KID_HSI_RANGE_DEC						274
#define KID_HUD_NAVFLIR_VIDEO					275
#define	KID_HUD_CAMERA_VIDEO					276
#define KID_TSD_PLANE_POSITION					277
#define	KID_TSD_RANGE_INC						278
#define KID_TSD_RANGE_DEC						279
#define	KID_TSD_DECLUTTER						280
#define KID_TSD_INVERSE_VIDEO					281
#define	KID_TSD_LOOK_AHEAD						282
#define	KID_MAIN_IFF_ITERR						283
#define KID_MAIN_TERRAIN_FOLLOW					284
#define	KID_MAIN_ILS							285
#define KID_MAIN_NAVFLIR						286
#define	KID_MAIN_STEER_POINT					287
#define KID_MAIN_DATA							288
#define	KID_MAIN_UFC							289
#define KID_MAIN_EMIS_LIMIT						290
#define KID_DATA_STERR_POINT					291
#define	KID_DATA_LOOK_AHEAD						292
#define KID_DATA_TIME_SELECT					293
#define	KID_DATA_TOA_TOT						294
#define KID_DATA_FUEL_BEARING					295
#define	KID_DATA_ETE_ETA						296
#define KID_DATA_FUEL_REMAIN					297
#define KID_AP_ENABLE_STEERING					298
#define	KID_AP_ALTITUDE_HOLD					299
#define KID_AP_ALTITUDE_SOURCE					300
#define	KID_HUD_GROUNDSPEED						301
#define KID_HUD_TRUE_AIRSPEED					302
#define	KID_HUD_RADAR_ALTIMETER					303
#define	KID_TEWS_DECLUTTER						304
#define KID_TEWS_RANGE_SELECT					305
#define	KID_TEWS_CMDS_MODE						306
#define	KID_RADAR_STBY_XMIT						307
#define	KID_MASTER_LEFT_ENGINE					308
#define KID_MASTER_RIGHT_ENGINE					309
#define KID_THROTTLE_OFF						310
#define	KID_THROTTLE_IDLE						311
#define KID_THROTTLE_MIL						312
#define	KID_THROTTLE_AB							313
#define	KID_THROTTLE_UP							314
#define KID_THROTTLE_DOWN						315
#define KID_THROTTLE_AB_UP						316
#define	KID_THROTTLE_AB_DN						317
#define	KID_THROTTLE_IDLE_RT					318
#define KID_THROTTLE_UP_RT						319
#define	KID_THROTTLE_DOWN_RT					320
#define KID_THROTTLE_MIL_RT						321
#define	KID_UNUSED3								322
#define	KID_THROTTLE_AB_UP_RT					323
#define KID_THROTTLE_AB_DN_RT					324
#define KID_IFF_AUTO_NORMAL						325
#define	KID_AIM9_SCAN							326
#define KID_GUN_SELECT							327
#define KID_OBJECT_COMPLEXITY					328
#define KID_SCENE_COMPLEXITY					329
#define KID_TOGGLE_SHADOWS                      330
#define KID_TOGGLE_ROADS	                    331
#define KID_TOGGLE_SPECTRAL                     332
#define KID_VIEW_DISTANCE						333
#define KID_TOGGLE_TRANSITIONS					334

#endif // __KEYMAPID_HEADER__